# application.yml 
---
# questo e' il profilo di default: 
lucky: 
  word: Default

---
spring: 
  profiles: english 
lucky: 
  word: Happy

---
spring: 
  profiles: italian 
lucky: 
  word: Evviva

